 
 -------------- celery@debian-hpelite v5.4.0 (opalescent)
--- ***** ----- 
-- ******* ---- Linux-5.10.0-32-amd64-x86_64-with-glibc2.31 2024-09-29 09:16:34
- *** --- * --- 
- ** ---------- [config]
- ** ---------- .> app:         conciergerie:0x7f09b20e66d0
- ** ---------- .> transport:   redis://localhost:6379/0
- ** ---------- .> results:     redis://localhost:6379/0
- *** --- * --- .> concurrency: 4 (prefork)
-- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
--- ***** ----- 
 -------------- [queues]
                .> celery           exchange=celery(direct) key=celery
                

[tasks]
  . services_menage.tasks.faire_etat_des_lieu_appart
  . services_menage.tasks.service_menage_task

[2024-09-29 09:16:35,033: INFO/MainProcess] Connected to redis://localhost:6379/0
[2024-09-29 09:16:35,036: INFO/MainProcess] mingle: searching for neighbors
[2024-09-29 09:16:36,047: INFO/MainProcess] mingle: all alone
[2024-09-29 09:16:36,079: INFO/MainProcess] celery@debian-hpelite ready.
[2024-09-29 09:21:58,617: INFO/MainProcess] Events of group {task} enabled by remote.
[E 240929 09:36:34 signal:280] Signal handler <bound method DjangoFixup.on_import_modules of <celery.fixups.django.DjangoFixup object at 0x7f6bc0734670>> raised: NameError("name 'PeriodicTask' is not defined")
    Traceback (most recent call last):
      File "/home/django/Depots/www/Back-end/Django/envCeleryConciergerie/lib/python3.9/site-packages/celery/utils/dispatch/signal.py", line 276, in send
        response = receiver(signal=self, sender=sender, **named)
      File "/home/django/Depots/www/Back-end/Django/envCeleryConciergerie/lib/python3.9/site-packages/celery/fixups/django.py", line 100, in on_import_modules
        self.worker_fixup.validate_models()
      File "/home/django/Depots/www/Back-end/Django/envCeleryConciergerie/lib/python3.9/site-packages/celery/fixups/django.py", line 140, in validate_models
        run_checks()
      File "/home/django/Depots/www/Back-end/Django/envCeleryConciergerie/lib/python3.9/site-packages/django/core/checks/registry.py", line 88, in run_checks
        new_errors = check(app_configs=app_configs, databases=databases)
      File "/home/django/Depots/www/Back-end/Django/envCeleryConciergerie/lib/python3.9/site-packages/django/core/checks/urls.py", line 14, in check_url_config
        return check_resolver(resolver)
      File "/home/django/Depots/www/Back-end/Django/envCeleryConciergerie/lib/python3.9/site-packages/django/core/checks/urls.py", line 24, in check_resolver
        return check_method()
      File "/home/django/Depots/www/Back-end/Django/envCeleryConciergerie/lib/python3.9/site-packages/django/urls/resolvers.py", line 494, in check
        for pattern in self.url_patterns:
      File "/home/django/Depots/www/Back-end/Django/envCeleryConciergerie/lib/python3.9/site-packages/django/utils/functional.py", line 57, in __get__
        res = instance.__dict__[self.name] = self.func(instance)
      File "/home/django/Depots/www/Back-end/Django/envCeleryConciergerie/lib/python3.9/site-packages/django/urls/resolvers.py", line 715, in url_patterns
        patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
      File "/home/django/Depots/www/Back-end/Django/envCeleryConciergerie/lib/python3.9/site-packages/django/utils/functional.py", line 57, in __get__
        res = instance.__dict__[self.name] = self.func(instance)
      File "/home/django/Depots/www/Back-end/Django/envCeleryConciergerie/lib/python3.9/site-packages/django/urls/resolvers.py", line 708, in urlconf_module
        return import_module(self.urlconf_name)
      File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
      File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
      File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
      File "<frozen importlib._bootstrap_external>", line 790, in exec_module
      File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
      File "/home/django/Depots/www/Back-end/Django/envCeleryConciergerie/conciergerie/conciergerie/urls.py", line 23, in <module>
        path('service/', include('services_menage.urls'))
      File "/home/django/Depots/www/Back-end/Django/envCeleryConciergerie/lib/python3.9/site-packages/django/urls/conf.py", line 38, in include
        urlconf_module = import_module(urlconf_module)
      File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
      File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
      File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
      File "<frozen importlib._bootstrap_external>", line 790, in exec_module
      File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
      File "/home/django/Depots/www/Back-end/Django/envCeleryConciergerie/conciergerie/services_menage/urls.py", line 7, in <module>
        from . import api_views
      File "/home/django/Depots/www/Back-end/Django/envCeleryConciergerie/conciergerie/services_menage/api_views.py", line 63, in <module>
        class PeriodicTaskViewSet(viewsets.ModelViewSet):
      File "/home/django/Depots/www/Back-end/Django/envCeleryConciergerie/conciergerie/services_menage/api_views.py", line 64, in PeriodicTaskViewSet
        queryset = PeriodicTask.objects.all()
    NameError: name 'PeriodicTask' is not defined
Traceback (most recent call last):
  File "/home/django/Depots/www/Back-end/Django/envCeleryConciergerie/bin/celery", line 8, in <module>
    sys.exit(main())
  File "/home/django/Depots/www/Back-end/Django/envCeleryConciergerie/lib/python3.9/site-packages/celery/__main__.py", line 15, in main
    sys.exit(_main())
  File "/home/django/Depots/www/Back-end/Django/envCeleryConciergerie/lib/python3.9/site-packages/celery/bin/celery.py", line 236, in main
    return celery(auto_envvar_prefix="CELERY")
  File "/home/django/Depots/www/Back-end/Django/envCeleryConciergerie/lib/python3.9/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/django/Depots/www/Back-end/Django/envCeleryConciergerie/lib/python3.9/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/django/Depots/www/Back-end/Django/envCeleryConciergerie/lib/python3.9/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/django/Depots/www/Back-end/Django/envCeleryConciergerie/lib/python3.9/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/django/Depots/www/Back-end/Django/envCeleryConciergerie/lib/python3.9/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/django/Depots/www/Back-end/Django/envCeleryConciergerie/lib/python3.9/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/django/Depots/www/Back-end/Django/envCeleryConciergerie/lib/python3.9/site-packages/flower/command.py", line 48, in flower
    flower_app = Flower(capp=app, options=options, **settings)
  File "/home/django/Depots/www/Back-end/Django/envCeleryConciergerie/lib/python3.9/site-packages/flower/app.py", line 50, in __init__
    self.capp.loader.import_default_modules()
  File "/home/django/Depots/www/Back-end/Django/envCeleryConciergerie/lib/python3.9/site-packages/celery/loaders/base.py", line 104, in import_default_modules
    raise response
  File "/home/django/Depots/www/Back-end/Django/envCeleryConciergerie/lib/python3.9/site-packages/celery/utils/dispatch/signal.py", line 276, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/home/django/Depots/www/Back-end/Django/envCeleryConciergerie/lib/python3.9/site-packages/celery/fixups/django.py", line 100, in on_import_modules
    self.worker_fixup.validate_models()
  File "/home/django/Depots/www/Back-end/Django/envCeleryConciergerie/lib/python3.9/site-packages/celery/fixups/django.py", line 140, in validate_models
    run_checks()
  File "/home/django/Depots/www/Back-end/Django/envCeleryConciergerie/lib/python3.9/site-packages/django/core/checks/registry.py", line 88, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "/home/django/Depots/www/Back-end/Django/envCeleryConciergerie/lib/python3.9/site-packages/django/core/checks/urls.py", line 14, in check_url_config
    return check_resolver(resolver)
  File "/home/django/Depots/www/Back-end/Django/envCeleryConciergerie/lib/python3.9/site-packages/django/core/checks/urls.py", line 24, in check_resolver
    return check_method()
  File "/home/django/Depots/www/Back-end/Django/envCeleryConciergerie/lib/python3.9/site-packages/django/urls/resolvers.py", line 494, in check
    for pattern in self.url_patterns:
  File "/home/django/Depots/www/Back-end/Django/envCeleryConciergerie/lib/python3.9/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/django/Depots/www/Back-end/Django/envCeleryConciergerie/lib/python3.9/site-packages/django/urls/resolvers.py", line 715, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/django/Depots/www/Back-end/Django/envCeleryConciergerie/lib/python3.9/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/django/Depots/www/Back-end/Django/envCeleryConciergerie/lib/python3.9/site-packages/django/urls/resolvers.py", line 708, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/django/Depots/www/Back-end/Django/envCeleryConciergerie/conciergerie/conciergerie/urls.py", line 23, in <module>
    path('service/', include('services_menage.urls'))
  File "/home/django/Depots/www/Back-end/Django/envCeleryConciergerie/lib/python3.9/site-packages/django/urls/conf.py", line 38, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/django/Depots/www/Back-end/Django/envCeleryConciergerie/conciergerie/services_menage/urls.py", line 7, in <module>
    from . import api_views 
  File "/home/django/Depots/www/Back-end/Django/envCeleryConciergerie/conciergerie/services_menage/api_views.py", line 63, in <module>
    class PeriodicTaskViewSet(viewsets.ModelViewSet):
  File "/home/django/Depots/www/Back-end/Django/envCeleryConciergerie/conciergerie/services_menage/api_views.py", line 64, in PeriodicTaskViewSet
    queryset = PeriodicTask.objects.all()
NameError: name 'PeriodicTask' is not defined
[I 240929 09:58:13 command:168] Visit me at http://0.0.0.0:5555
[I 240929 09:58:13 command:176] Broker: redis://localhost:6379/0
[I 240929 09:58:13 command:177] Registered tasks: 
    ['celery.accumulate',
     'celery.backend_cleanup',
     'celery.chain',
     'celery.chord',
     'celery.chord_unlock',
     'celery.chunks',
     'celery.group',
     'celery.map',
     'celery.starmap',
     'services_menage.tasks.faire_etat_des_lieu_appart',
     'services_menage.tasks.service_menage_task']
[I 240929 09:58:13 mixins:228] Connected to redis://localhost:6379/0
[I 240929 10:03:38 command:168] Visit me at http://0.0.0.0:5555
[I 240929 10:03:38 command:176] Broker: redis://localhost:6379/0
[I 240929 10:03:38 command:177] Registered tasks: 
    ['celery.accumulate',
     'celery.backend_cleanup',
     'celery.chain',
     'celery.chord',
     'celery.chord_unlock',
     'celery.chunks',
     'celery.group',
     'celery.map',
     'celery.starmap',
     'services_menage.tasks.faire_etat_des_lieu_appart',
     'services_menage.tasks.service_menage_task']
[I 240929 10:03:38 mixins:228] Connected to redis://localhost:6379/0
